import matplotlib.pyplot as plt

model = [plt.prism(-1000, 1000, -1000, 1000, 0, 2000, {'density': 100})]
area = (-5000, 5000, -5000, 5000)
shape = (51, 51)
z0 = -500
xp, yp, zp = plt.grid(area, shape, z=z0)
gz = plt.giutils.contaminate(plt.prism.gz(xp, yp, zp, model), 0.001)

# Need to convert gz to SI units so that the result can be converted to Eotvos
gxz = plt.giutils.si2eotvos(plt.pftrans.derivx(xp, yp, plt.giutils.mgal2si(gz), shape))
gyz = plt.giutils.si2eotvos(plt.pftrans.derivy(xp, yp, plt.giutils.mgal2si(gz), shape))
gzz = plt.giutils.si2eotvos(plt.pftrans.derivz(xp, yp, plt.giutils.mgal2si(gz), shape))

gxz_true = plt.prism.gxz(xp, yp, zp, model)
gyz_true = plt.prism.gyz(xp, yp, zp, model)
gzz_true = plt.prism.gzz(xp, yp, zp, model)

plt.figure()
plt.title("Original gravity anomaly")
plt.axis('scaled')
plt.contourf(xp, yp, gz, shape, 15)
plt.colorbar(shrink=0.7)
plt.m2km()
plt.figure(figsize=(14, 10))
plt.subplots_adjust(top=0.95, left=0.05, right=0.95)
plt.subplot(2, 3, 1)
plt.title("x deriv (contour) + true (color map)")
plt.axis('scaled')
levels = plt.contourf(yp, xp, gxz_true, shape, 12)
plt.colorbar(shrink=0.7)
plt.contour(yp, xp, gxz, shape, 12, color='k')
plt.m2km()
plt.subplot(2, 3, 2)
plt.title("y deriv (contour) + true (color map)")
plt.axis('scaled')
levels = plt.contourf(yp, xp, gyz_true, shape, 12)
plt.colorbar(shrink=0.7)
plt.contour(yp, xp, gyz, shape, 12, color='k')
plt.m2km()
plt.subplot(2, 3, 3)
plt.title("z deriv (contour) + true (color map)")
plt.axis('scaled')
levels = plt.contourf(yp, xp, gzz_true, shape, 8)
plt.colorbar(shrink=0.7)
plt.contour(yp, xp, gzz, shape, levels, color='k')
plt.m2km()
plt.subplot(2, 3, 4)
plt.title("Difference x deriv")
plt.axis('scaled')
plt.pcolor(yp, xp, (gxz_true - gxz), shape)
plt.colorbar(shrink=0.7)
plt.m2km()
plt.subplot(2, 3, 5)
plt.title("Difference y deriv")
plt.axis('scaled')
plt.pcolor(yp, xp, (gyz_true - gyz), shape)
plt.colorbar(shrink=0.7)
plt.m2km()
plt.subplot(2, 3, 6)
plt.title("Difference z deriv")
plt.axis('scaled')
plt.pcolor(yp, xp, (gzz_true - gzz), shape)
plt.colorbar(shrink=0.7)
plt.m2km()
plt.show()